### ISSUE TITLE
Undefined array key "address"

### ISSUE THREAD

**Issue by premiumwatchdevice** [sdkconsultoria/whatsapp-cloud-api#2]
Undefined array key "address" when get the url ini with waba id

```
$app = require_once __DIR__.'/../bootstrap/app.php';



$kernel = $app->make(Kernel::class);



$response = $kernel->handle(

    $request = Request::capture()

)->send();



$kernel->terminate($request, $response);
```

**Comment by hellsythe** [comment]
I will correct the error today. Thanks for the warning.

This happens because INIT

- Load the waba information
- Load the templates
- Load the information of the numbers
- Load the business profile of the numbers - here is the error because If you are using a test number it does not have a business profile.

-------
You can do the following to bypass the bug:

Run in order

{{HOST}}/api/v1/waba/{{wabaId}}/get-info
{{HOST}}/api/v1/waba/{{wabaId}}/get-templates
{{HOST}}/api/v1/waba/{{wabaId}}/get-phones // this will give you the same error but ignore it and you will be able to send the messages

**Comment by hellsythe** [comment]
The bug was fixed
